/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotel.management.system;

import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class AddCustomer extends javax.swing.JFrame {

    /**
     * Creates new form AddCustomer
     */
    public AddCustomer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt1 = new javax.swing.JLabel();
        combo3 = new javax.swing.JComboBox<>();
        name2 = new javax.swing.JTextField();
        txt2 = new javax.swing.JLabel();
        txt3 = new javax.swing.JLabel();
        txt4 = new javax.swing.JLabel();
        txt5 = new javax.swing.JLabel();
        txt6 = new javax.swing.JLabel();
        name6 = new javax.swing.JTextField();
        name1 = new javax.swing.JTextField();
        name4 = new javax.swing.JTextField();
        txt7 = new javax.swing.JLabel();
        txt8 = new javax.swing.JLabel();
        name9 = new javax.swing.JTextField();
        name5 = new javax.swing.JTextField();
        btnon1 = new javax.swing.JButton();
        btnon = new javax.swing.JButton();
        rd2 = new javax.swing.JRadioButton();
        rd1 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        txt9 = new javax.swing.JLabel();
        name8 = new javax.swing.JTextField();
        btnon2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("Customer Room");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(80, 30, 150, 30);

        txt1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        txt1.setText("Check-in Time");
        jPanel1.add(txt1);
        txt1.setBounds(50, 360, 170, 20);

        combo3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PassPort", "DriverLicense", "AadharCard", "VoterIdCard", "RationCard" }));
        jPanel1.add(combo3);
        combo3.setBounds(260, 90, 170, 30);
        jPanel1.add(name2);
        name2.setBounds(260, 170, 170, 30);

        txt2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        txt2.setText("Number");
        jPanel1.add(txt2);
        txt2.setBounds(70, 140, 90, 20);

        txt3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        txt3.setText("Gender");
        jPanel1.add(txt3);
        txt3.setBounds(70, 220, 90, 20);

        txt4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        txt4.setText("Country");
        jPanel1.add(txt4);
        txt4.setBounds(70, 270, 90, 20);

        txt5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        txt5.setText("Govt. ID");
        jPanel1.add(txt5);
        txt5.setBounds(70, 100, 90, 20);

        txt6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        txt6.setText("Name");
        jPanel1.add(txt6);
        txt6.setBounds(70, 180, 90, 20);
        jPanel1.add(name6);
        name6.setBounds(260, 350, 170, 30);

        name1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name1ActionPerformed(evt);
            }
        });
        jPanel1.add(name1);
        name1.setBounds(260, 130, 170, 30);
        jPanel1.add(name4);
        name4.setBounds(260, 260, 170, 30);

        txt7.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        txt7.setText("Customer Unique ID");
        jPanel1.add(txt7);
        txt7.setBounds(40, 450, 170, 20);

        txt8.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        txt8.setText("Allocate Room Number");
        jPanel1.add(txt8);
        txt8.setBounds(50, 310, 170, 20);
        jPanel1.add(name9);
        name9.setBounds(260, 440, 170, 30);
        jPanel1.add(name5);
        name5.setBounds(260, 300, 170, 30);

        btnon1.setBackground(new java.awt.Color(0, 0, 0));
        btnon1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnon1.setForeground(new java.awt.Color(255, 255, 255));
        btnon1.setText("Cancel");
        btnon1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnon1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnon1);
        btnon1.setBounds(310, 510, 130, 30);

        btnon.setBackground(new java.awt.Color(0, 0, 0));
        btnon.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnon.setForeground(new java.awt.Color(255, 255, 255));
        btnon.setText("Add Customer");
        btnon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnonActionPerformed(evt);
            }
        });
        jPanel1.add(btnon);
        btnon.setBounds(160, 510, 130, 30);

        rd2.setText("Male");
        jPanel1.add(rd2);
        rd2.setBounds(360, 220, 70, 21);

        rd1.setText("Female");
        jPanel1.add(rd1);
        rd1.setBounds(260, 220, 70, 21);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screenshot 2024-05-16 141734.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(450, 20, 480, 510);

        txt9.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        txt9.setText("Deposit");
        jPanel1.add(txt9);
        txt9.setBounds(50, 400, 170, 20);
        jPanel1.add(name8);
        name8.setBounds(260, 390, 170, 30);

        btnon2.setBackground(new java.awt.Color(0, 0, 0));
        btnon2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnon2.setForeground(new java.awt.Color(255, 255, 255));
        btnon2.setText("Back");
        btnon2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnon2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnon2);
        btnon2.setBounds(20, 510, 120, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 938, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void name1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name1ActionPerformed

    private void btnonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnonActionPerformed
       
         Connection con =null;
        PreparedStatement pmt=null;
            String id = (String) combo3.getSelectedItem();
            long num1 = Long.parseLong(name1.getText());
            String name=name2.getText();
             String gen=null;
                if(rd2.isSelected()){
                    gen="Male";
                }else if(rd1.isSelected()){
                    gen="Female";
}
            String cnty= name4.getText();
            int nu = Integer.parseInt(name5.getText());
            String time=name6.getText();
            String dep=name8.getText();
            String ide=name9.getText();
        if (name1.getText().isEmpty() ||  name2.getText().isEmpty() || name4.getText().isEmpty() || name5.getText().isEmpty() || name6.getText().isEmpty()|| name8.getText().isEmpty() || name9.getText().isEmpty()){
        JOptionPane.showMessageDialog(this, "Incomplete registration details please fill the form completely");
    }
        else{
        
            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel", "root", "admin");
                pmt=con.prepareStatement("insert into  custoomer values(?,?,?,?,?,?,?,?,?)");
                pmt.setString(1,id);
                pmt.setString(2,name);
                pmt.setString(3,gen);
                pmt.setString(4,cnty);
                pmt.setInt(5,nu);
                pmt.setString(6,time);
                pmt.setString(7,dep);
                pmt.setLong(8,num1);
                pmt.setString(9,ide);
                pmt.executeUpdate();
                JOptionPane.showMessageDialog(this, "Data Saved Successfully !!");
                pmt.close();
                con.close();
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(AddCustomer.class.getName()).log(Level.SEVERE, null, ex);
            }}
              
    }//GEN-LAST:event_btnonActionPerformed

    private void btnon1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnon1ActionPerformed
        name1.setText("");
        name2.setText("");
        name4.setText("");
        name5.setText("");
        name6.setText("");
        name9.setText("");
    }//GEN-LAST:event_btnon1ActionPerformed

    private void btnon2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnon2ActionPerformed
        new thirdpage().setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_btnon2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String  args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnon;
    private javax.swing.JButton btnon1;
    private javax.swing.JButton btnon2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> combo3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField name1;
    private javax.swing.JTextField name2;
    private javax.swing.JTextField name4;
    private javax.swing.JTextField name5;
    private javax.swing.JTextField name6;
    private javax.swing.JTextField name8;
    private javax.swing.JTextField name9;
    private javax.swing.JRadioButton rd1;
    private javax.swing.JRadioButton rd2;
    private javax.swing.JLabel txt1;
    private javax.swing.JLabel txt2;
    private javax.swing.JLabel txt3;
    private javax.swing.JLabel txt4;
    private javax.swing.JLabel txt5;
    private javax.swing.JLabel txt6;
    private javax.swing.JLabel txt7;
    private javax.swing.JLabel txt8;
    private javax.swing.JLabel txt9;
    // End of variables declaration//GEN-END:variables
}
