/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotel.management.system;

import hotel.management.system.CustomerInfo;
import java.awt.Choice;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Lenovo
 */
public class DriverInfo extends javax.swing.JFrame {
Connection c =null;
Statement stmt=null;
    Choice drive;
    JTable table;
    public DriverInfo() {
        drive = new Choice();
        drive.setBounds(100, 75, 110, 120);
        add(drive);
        try{
        c = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel", "root", "admin");
        stmt = c.createStatement();
ResultSet rs1 = stmt.executeQuery("SELECT * FROM driver");
while(rs1.next()){
        drive.add(rs1.getString("carmodel"));
}      
    }   catch (SQLException ex) {
            Logger.getLogger(DriverInfo.class.getName()).log(Level.SEVERE, null, ex);
        }
try{
        table= new JTable ();
            table.setBounds(0,150,1000,500);
            add(table);
            Connection c1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel", "root", "admin");
Statement smt = c1.createStatement();
ResultSet rs = smt.executeQuery("SELECT * FROM driver");
table.setModel(DbUtils.resultSetToTableModel(rs));
    }   catch (SQLException ex) {
            Logger.getLogger(CustomerInfo.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tbn2 = new javax.swing.JButton();
        tbn1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setText("PickUp Service");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(390, 10, 130, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel3.setText("Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 110, 90, 30);

        tbn2.setBackground(new java.awt.Color(0, 0, 0));
        tbn2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        tbn2.setForeground(new java.awt.Color(255, 255, 255));
        tbn2.setText("Back");
        tbn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbn2ActionPerformed(evt);
            }
        });
        jPanel1.add(tbn2);
        tbn2.setBounds(470, 660, 150, 30);

        tbn1.setBackground(new java.awt.Color(0, 0, 0));
        tbn1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        tbn1.setForeground(new java.awt.Color(255, 255, 255));
        tbn1.setText("Submit");
        tbn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbn1ActionPerformed(evt);
            }
        });
        jPanel1.add(tbn1);
        tbn1.setBounds(280, 660, 150, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel4.setText("Age");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(150, 110, 40, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel5.setText("Gender");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(280, 110, 90, 30);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel6.setText("Company");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(420, 110, 90, 30);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel7.setText("Address");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(860, 110, 90, 30);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel8.setText("Brand");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(40, 70, 90, 30);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel9.setText("Model");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(570, 110, 90, 30);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel10.setText("Availability");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(700, 110, 90, 30);

        jLabel1.setBackground(new java.awt.Color(0, 153, 204));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 990, 700);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 987, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tbn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbn1ActionPerformed
        
            Connection con=null;
            Statement sm=null;
            ResultSet rs2=null;
            String d = drive.getSelectedItem();
        try{
         con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel", "root", "admin");
         sm = con.createStatement();
ResultSet rs = sm.executeQuery("SELECT * FROM driver where carmodel ="+"'"+d+"'");
table.setModel(DbUtils.resultSetToTableModel(rs));   
        }
        catch (SQLException ex) {
            Logger.getLogger(CustomerInfo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tbn1ActionPerformed

    private void tbn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbn2ActionPerformed
        Reception r=new Reception();
        r.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_tbn2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DriverInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DriverInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DriverInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DriverInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DriverInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton tbn1;
    private javax.swing.JButton tbn2;
    // End of variables declaration//GEN-END:variables
}
