/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotel.management.system;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
public class ThirdTwo extends javax.swing.JFrame {

    Connection con= null;
    PreparedStatement psmt=null;
    public ThirdTwo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        clean = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        roomno = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        adbox2 = new javax.swing.JComboBox<>();
        ava = new javax.swing.JLabel();
        adbox1 = new javax.swing.JComboBox<>();
        clean1 = new javax.swing.JLabel();
        txtroom = new javax.swing.JTextField();
        clean2 = new javax.swing.JLabel();
        adbox3 = new javax.swing.JComboBox<>();
        can = new javax.swing.JButton();
        sub = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        clean.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        clean.setText("Bed Type");
        jPanel1.add(clean);
        clean.setBounds(50, 320, 100, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel3.setText("Add Rooms");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(130, 50, 190, 30);

        roomno.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        roomno.setText("Room Number");
        jPanel1.add(roomno);
        roomno.setBounds(50, 120, 100, 30);

        price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceActionPerformed(evt);
            }
        });
        jPanel1.add(price);
        price.setBounds(190, 270, 170, 30);

        adbox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single Bed", "Double Bed", " " }));
        jPanel1.add(adbox2);
        adbox2.setBounds(190, 320, 170, 30);

        ava.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        ava.setText("Available");
        jPanel1.add(ava);
        ava.setBounds(50, 170, 100, 30);

        adbox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Available", "Occupied" }));
        jPanel1.add(adbox1);
        adbox1.setBounds(190, 170, 170, 30);

        clean1.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        clean1.setText("Cleaning Status");
        jPanel1.add(clean1);
        clean1.setBounds(50, 220, 100, 30);

        txtroom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtroomActionPerformed(evt);
            }
        });
        jPanel1.add(txtroom);
        txtroom.setBounds(190, 120, 170, 30);

        clean2.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        clean2.setText("Price");
        jPanel1.add(clean2);
        clean2.setBounds(50, 270, 100, 30);

        adbox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cleaned", "Dirty" }));
        jPanel1.add(adbox3);
        adbox3.setBounds(190, 220, 170, 30);

        can.setBackground(new java.awt.Color(0, 0, 0));
        can.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        can.setForeground(new java.awt.Color(255, 255, 255));
        can.setText("Cancel");
        can.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canActionPerformed(evt);
            }
        });
        jPanel1.add(can);
        can.setBounds(230, 410, 140, 30);

        sub.setBackground(new java.awt.Color(0, 0, 0));
        sub.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        sub.setForeground(new java.awt.Color(255, 255, 255));
        sub.setText("Add Room");
        sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subActionPerformed(evt);
            }
        });
        jPanel1.add(sub);
        sub.setBounds(30, 410, 140, 30);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot 2024-05-13 232901.png"))); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(280, 450));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(410, 10, 680, 460);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1104, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceActionPerformed

    private void txtroomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtroomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtroomActionPerformed

    private void canActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canActionPerformed
         txtroom.setText("");
        price.setText("");
    }//GEN-LAST:event_canActionPerformed

    private void subActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subActionPerformed
       String room = txtroom.getText();
        String box1= (String) adbox1.getSelectedItem();
        String box2= (String) adbox2.getSelectedItem();
        int rupee= Integer.parseInt(price.getText());
        String box3= (String) adbox3.getSelectedItem();
        if(room.isEmpty() || box1.isEmpty() || box2.isEmpty() || box3.isEmpty()){
        JOptionPane.showMessageDialog(this, "Incomplete registration details please fill the form completely");
    }
        else{
            try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel", "root", "admin");
                psmt=con.prepareStatement("insert into room values(?,?,?,?,?)");
                psmt.setString(4, txtroom.getText());
                psmt.setString(5, (String) adbox1.getSelectedItem());
                psmt.setInt(2, Integer.parseInt(price.getText()));
                psmt.setString(3, (String) adbox2.getSelectedItem());
                psmt.setString(1, (String) adbox3.getSelectedItem());
                psmt.executeUpdate();
                JOptionPane.showMessageDialog(this, "Data Saved Successfully !!");
                psmt.close();
                con.close();
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(ThirdTwo.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_subActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThirdTwo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThirdTwo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThirdTwo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThirdTwo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThirdTwo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> adbox1;
    private javax.swing.JComboBox<String> adbox2;
    private javax.swing.JComboBox<String> adbox3;
    private javax.swing.JLabel ava;
    private javax.swing.JButton can;
    private javax.swing.JLabel clean;
    private javax.swing.JLabel clean1;
    private javax.swing.JLabel clean2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField price;
    private javax.swing.JLabel roomno;
    private javax.swing.JButton sub;
    private javax.swing.JTextField txtroom;
    // End of variables declaration//GEN-END:variables
}
