/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotel.management.system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class ThirdOne extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement pmt = null;
    public ThirdOne() {
        initComponents();
       
        ButtonGroup bg = new ButtonGroup();
        bg.add(erbtn);
        bg.add(erbtn2); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        age = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        label2 = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        erbtn2 = new javax.swing.JRadioButton();
        erbtn = new javax.swing.JRadioButton();
        edrop = new javax.swing.JComboBox<>();
        label5 = new javax.swing.JLabel();
        eide = new javax.swing.JTextField();
        label6 = new javax.swing.JLabel();
        eemail = new javax.swing.JTextField();
        eage = new javax.swing.JTextField();
        ephone = new javax.swing.JTextField();
        label7 = new javax.swing.JLabel();
        label8 = new javax.swing.JLabel();
        label9 = new javax.swing.JLabel();
        esalary = new javax.swing.JTextField();
        Submit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        label10 = new javax.swing.JLabel();
        etxtname = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        label2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        label2.setText("EMAIL");
        jPanel1.add(label2);
        label2.setBounds(50, 390, 70, 20);

        label4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        label4.setText("AGE");
        jPanel1.add(label4);
        label4.setBounds(60, 110, 60, 20);

        erbtn2.setText("FEMALE");
        erbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                erbtn2ActionPerformed(evt);
            }
        });
        jPanel1.add(erbtn2);
        erbtn2.setBounds(300, 160, 98, 21);

        erbtn.setText("MALE");
        erbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                erbtnActionPerformed(evt);
            }
        });
        jPanel1.add(erbtn);
        erbtn.setBounds(210, 160, 60, 21);

        edrop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Front Desk Clerks", "Housekeeping", "Kitchen Staff", "Room Services", "Chefs", "waiter/Waiteress", "Manager", "Accountant" }));
        edrop.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                edropComponentAdded(evt);
            }
        });
        edrop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edropActionPerformed(evt);
            }
        });
        jPanel1.add(edrop);
        edrop.setBounds(200, 200, 210, 30);

        label5.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        label5.setText("GENDER");
        jPanel1.add(label5);
        label5.setBounds(50, 160, 100, 20);
        jPanel1.add(eide);
        eide.setBounds(200, 240, 210, 30);

        label6.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        label6.setText("JOB");
        jPanel1.add(label6);
        label6.setBounds(60, 200, 60, 20);
        jPanel1.add(eemail);
        eemail.setBounds(200, 390, 210, 30);
        jPanel1.add(eage);
        eage.setBounds(200, 110, 210, 30);
        jPanel1.add(ephone);
        ephone.setBounds(200, 290, 210, 30);

        label7.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        label7.setText("ID");
        jPanel1.add(label7);
        label7.setBounds(70, 250, 70, 20);

        label8.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        label8.setText("PHONE NO.");
        jPanel1.add(label8);
        label8.setBounds(50, 300, 110, 20);

        label9.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        label9.setText("SALARY");
        jPanel1.add(label9);
        label9.setBounds(50, 350, 70, 20);
        jPanel1.add(esalary);
        esalary.setBounds(200, 340, 210, 30);

        Submit.setBackground(new java.awt.Color(0, 0, 0));
        Submit.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        Submit.setForeground(new java.awt.Color(255, 255, 255));
        Submit.setText("SUBMIT");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        jPanel1.add(Submit);
        Submit.setBounds(200, 460, 210, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot 2024-05-12 231238.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(470, 20, 560, 520);

        label10.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        label10.setText("NAME");
        jPanel1.add(label10);
        label10.setBounds(60, 70, 80, 20);

        etxtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etxtnameActionPerformed(evt);
            }
        });
        jPanel1.add(etxtname);
        etxtname.setBounds(200, 60, 210, 30);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setText("ADD EMPLOYEE");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(130, 10, 190, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1091, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageActionPerformed

    private void erbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_erbtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_erbtn2ActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        
        if (etxtname.getText().isEmpty() || eage.getText().isEmpty() || eemail.getText().isEmpty() || ephone.getText().isEmpty() || eide.getText().isEmpty()){
        JOptionPane.showMessageDialog(this, "Incomplete registration details please fill the form completely");
    }
        else{
            try {
                String name = etxtname.getText();
                 String age = eage.getText();
                String drop = (String)edrop.getSelectedItem();
                String id = eide.getText();
                long x= Long.parseLong(ephone.getText());
                int sal = Integer.parseInt(esalary.getText());
                String email = eemail.getText();
                
                String gen=null;
                if(erbtn.isSelected()){
                    gen="Male";
                }else if(erbtn2.isSelected()){
                    gen="Female";
                }
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel", "root", "admin");
                pmt=con.prepareStatement("insert into employee values(?,?,?,?,?,?,?,?)");
                pmt.setString(1,name);
                pmt.setString(2,age);
                pmt.setString(3,gen);
                pmt.setString(5,drop);
                pmt.setString(4,id);
                pmt.setLong(6,x);
                pmt.setLong(8,sal);
                pmt.setString(7,email);
                pmt.executeUpdate();
                JOptionPane.showMessageDialog(this, "Data Saved Successfully !!");
                pmt.close();
                con.close();
             }catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(ThirdOne.class.getName()).log(Level.SEVERE, null, ex);
        } }
    }//GEN-LAST:event_SubmitActionPerformed

    private void etxtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etxtnameActionPerformed
        
    }//GEN-LAST:event_etxtnameActionPerformed

    private void erbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_erbtnActionPerformed
       
    }//GEN-LAST:event_erbtnActionPerformed

    private void edropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edropActionPerformed
      
    }//GEN-LAST:event_edropActionPerformed

    private void edropComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_edropComponentAdded

    }//GEN-LAST:event_edropComponentAdded

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThirdOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThirdOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThirdOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThirdOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThirdOne().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Submit;
    private javax.swing.JTextField age;
    private javax.swing.JTextField eage;
    private javax.swing.JComboBox<String> edrop;
    private javax.swing.JTextField eemail;
    private javax.swing.JTextField eide;
    private javax.swing.JTextField ephone;
    private javax.swing.JRadioButton erbtn;
    private javax.swing.JRadioButton erbtn2;
    private javax.swing.JTextField esalary;
    private javax.swing.JTextField etxtname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label10;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label6;
    private javax.swing.JLabel label7;
    private javax.swing.JLabel label8;
    private javax.swing.JLabel label9;
    // End of variables declaration//GEN-END:variables
}
