/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotel.management.system;

import java.awt.Choice;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


public class UpdateRoom extends javax.swing.JFrame {

    Choice ccustomer;
    public UpdateRoom(){
        ccustomer = new Choice();
        ccustomer.setBounds(240, 100, 165, 120);
        add(ccustomer);
        try{
        Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel", "root", "admin");
Statement stmt = c.createStatement();
ResultSet rs = stmt.executeQuery("SELECT * FROM custoomer");
while(rs.next()){
        ccustomer.add(rs.getString("customerid"));
}
        } catch (SQLException ex) {
            Logger.getLogger(UpdateRoom.class.getName()).log(Level.SEVERE, null, ex);            
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        xtx1 = new javax.swing.JTextField();
        xtx2 = new javax.swing.JTextField();
        xtx3 = new javax.swing.JTextField();
        xtx4 = new javax.swing.JTextField();
        xtx5 = new javax.swing.JTextField();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel1.setText("Update Status");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(130, 10, 160, 50);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel2.setText("Room Number");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 150, 100, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel3.setText("Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 200, 100, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel4.setText("Check-In Time");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(60, 250, 100, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel5.setText("Pending Amount ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(60, 350, 120, 30);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel6.setText("Customer ID");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(60, 100, 100, 30);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel7.setText("Amount Paid");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(60, 300, 100, 30);

        xtx1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jPanel1.add(xtx1);
        xtx1.setBounds(240, 200, 170, 30);

        xtx2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jPanel1.add(xtx2);
        xtx2.setBounds(240, 250, 170, 30);

        xtx3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jPanel1.add(xtx3);
        xtx3.setBounds(240, 300, 170, 30);

        xtx4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jPanel1.add(xtx4);
        xtx4.setBounds(240, 350, 170, 30);

        xtx5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jPanel1.add(xtx5);
        xtx5.setBounds(240, 150, 170, 30);

        btn1.setBackground(new java.awt.Color(0, 0, 0));
        btn1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btn1.setForeground(new java.awt.Color(255, 255, 255));
        btn1.setText("Update");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn1);
        btn1.setBounds(180, 430, 130, 30);

        btn2.setBackground(new java.awt.Color(0, 0, 0));
        btn2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btn2.setForeground(new java.awt.Color(255, 255, 255));
        btn2.setText("Back");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        jPanel1.add(btn2);
        btn2.setBounds(340, 430, 130, 30);

        btn3.setBackground(new java.awt.Color(0, 0, 0));
        btn3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btn3.setForeground(new java.awt.Color(255, 255, 255));
        btn3.setText("Check");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        jPanel1.add(btn3);
        btn3.setBounds(20, 430, 130, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nine.jpg"))); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(470, 80, 470, 280);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 957, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        String id = ccustomer.getSelectedItem();
        String r= xtx5.getText();
        String w=xtx1.getText();
        String p=xtx4.getText();
        String e=xtx3.getText();
        try{
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel", "root", "admin");
        Statement  smt = con.createStatement();
        smt.executeUpdate("update custoomer set alocate ="+r+",name ="+w+", checkin ="+xtx2+", depositt ="+xtx3);
        JOptionPane.showMessageDialog(null, "Data Update Successfully !!");
        }catch (SQLException ex) {
            Logger.getLogger(UpdateRoom.class.getName()).log(Level.SEVERE, null, ex);            
        }
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
String id = ccustomer.getSelectedItem();
String d= xtx3.getText();
        try{
         Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel", "root", "admin");
 Statement  smt = con.createStatement();
ResultSet rs3 = smt.executeQuery("SELECT * FROM custoomer where customerid ="+"'"+id+"'");
while(rs3.next()){
        xtx5.setText(rs3.getString("alocate"));
        xtx1.setText(rs3.getString("namer"));
        xtx2.setText(rs3.getString("checkin"));
        xtx3.setText(rs3.getString("depositt"));
        
}
rs3.close();
ResultSet rs2 = smt.executeQuery("SELECT * FROM room where roomid ="+"'"+id+"'");
while(rs2.next()){
        int i=Integer.parseInt("price") - Integer.parseInt(d) ;
        xtx4.setText(rs3.getString(i));
}
rs2.close();
smt.close();
con.close();
        } catch (SQLException ex) {
            Logger.getLogger(UpdateRoom.class.getName()).log(Level.SEVERE, null, ex);            
        }
        
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        Reception c=new Reception();
        c.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateRoom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField xtx1;
    private javax.swing.JTextField xtx2;
    private javax.swing.JTextField xtx3;
    private javax.swing.JTextField xtx4;
    private javax.swing.JTextField xtx5;
    // End of variables declaration//GEN-END:variables
}
