/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotel.management.system;

import java.awt.Choice;
import java.sql.Connection;
//import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class UpdateRoomCustomer extends javax.swing.JFrame {
//PreparedStatement psmt = null ;
Connection c=null;
Statement stmt=null;
    Choice croom;
    public UpdateRoomCustomer() {
        croom = new Choice();
        croom.setBounds(260, 130, 175, 130);
        add(croom);
        try{
        c = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel", "root", "admin");
        stmt = c.createStatement();
ResultSet rs1 = stmt.executeQuery("SELECT * FROM custoomer");
while(rs1.next()){
        croom.add(rs1.getString("customerid"));
}
rs1.close();
stmt.close();
c.close();
        } catch (SQLException ex) {
            Logger.getLogger(UpdateRoom.class.getName()).log(Level.SEVERE, null, ex);            
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtavail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtclean = new javax.swing.JTextField();
        txtid = new javax.swing.JTextField();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screenshot 2024-05-19 134336.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(480, 50, 690, 330);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setText("Update Room Status");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(130, 40, 200, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel3.setText("Room Number");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 180, 100, 30);
        jPanel1.add(txtavail);
        txtavail.setBounds(260, 230, 170, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel4.setText("Availability");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(70, 230, 90, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel5.setText("Cleaning Status");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(60, 280, 110, 30);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel6.setText("Guest ID");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(70, 130, 90, 30);
        jPanel1.add(txtclean);
        txtclean.setBounds(260, 280, 170, 30);

        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });
        jPanel1.add(txtid);
        txtid.setBounds(260, 180, 170, 30);

        btn5.setBackground(new java.awt.Color(0, 0, 0));
        btn5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btn5.setForeground(new java.awt.Color(255, 255, 255));
        btn5.setText("Update");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        jPanel1.add(btn5);
        btn5.setBounds(180, 370, 130, 30);

        btn6.setBackground(new java.awt.Color(0, 0, 0));
        btn6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btn6.setForeground(new java.awt.Color(255, 255, 255));
        btn6.setText("Back");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        jPanel1.add(btn6);
        btn6.setBounds(340, 370, 130, 30);

        btn4.setBackground(new java.awt.Color(0, 0, 0));
        btn4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btn4.setForeground(new java.awt.Color(255, 255, 255));
        btn4.setText("Check");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        jPanel1.add(btn4);
        btn4.setBounds(20, 370, 130, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        
        String id = croom.getSelectedItem();
        try{
         c = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel", "root", "admin");
         stmt = c.createStatement();
ResultSet rs = stmt.executeQuery("SELECT * FROM custoomer where customerid ="+"'"+id+"'");
while(rs.next()){
        txtid.setText(rs.getString("alocate"));
}
rs.close();
ResultSet rs2 = stmt.executeQuery("SELECT * FROM room where roomid ="+txtid.getText());
while(rs2.next()){
        txtavail.setText(rs2.getString("avale"));
        txtclean.setText(rs2.getString("cleaning"));

}
rs2.close();
stmt.close();
c.close();
        } catch (SQLException ex) {
            Logger.getLogger(UpdateRoom.class.getName()).log(Level.SEVERE, null, ex);            
        }

    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        String room = croom.getSelectedItem();
        String id= txtid.getText();
        String avail= txtavail.getText();
        String clean=txtclean.getText();
        try{
        c = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel", "root", "admin");
        stmt=c.createStatement();
        stmt.executeUpdate("update room set avale =" + avail + " and cleaning =" + clean + " where roomid =" + id);
        JOptionPane.showMessageDialog(this, "Data Saved Successfully !!");
        
        } catch (SQLException ex) {
            Logger.getLogger(UpdateRoom.class.getName()).log(Level.SEVERE, null, ex);            
        }
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
            Reception r=new Reception();
            r.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_btn6ActionPerformed

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateRoomCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateRoomCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateRoomCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateRoomCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateRoomCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtavail;
    private javax.swing.JTextField txtclean;
    private javax.swing.JTextField txtid;
    // End of variables declaration//GEN-END:variables
}
